# NumPy

Numeric Python

In [ ]:
list  - collection of different type of elements
array - collection of similar type of elements

In [1]:
!pip install numpy

### 1 - Creating a vector

In [2]:
import numpy as np

In [5]:
# help(np.array)

In [6]:
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [7]:
print(type(v))

<class 'numpy.ndarray'>


In [8]:
v = np.array([[1],[2],[3]])

v

array([[1],
       [2],
       [3]])

### 2 - Matrix

In [9]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
0th dimension ----->    .
1st dimension ----->    ._________.   # number line

2nd dimension ----->    .____|_____.

3rd dimension ----->    ._____|_____.
                             /

4th dimension ----->
.
.
.
nth dimensions

In [ ]:
# what is the real world example of linear algebra (matrix)
1080p

720p

### 3 - Describe Matrix

In [11]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix.shape

(3, 3)

In [13]:
matrix.size

9

In [14]:
matrix.ndim

2

### 4 - Max and Min Values

In [15]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(np.max(matrix))

9


In [17]:
print(np.min(matrix))

1


### 5 - Statistics

In [ ]:
1. Descriptive -> Mean, Median, Mode, Standard Deviation, Variance, IQR, Percentile

2. Inferential -> models, hypothesis testing, regression(relationship)

In [18]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print(np.mean(matrix))

5.0


In [21]:
print(np.std(matrix))

2.581988897471611


In [22]:
print(np.var(matrix))

6.666666666666667


### 6 - Reshaping arrays

In [23]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [25]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [26]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [27]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


In [ ]:
## Assignment
Folder - Numpy books

solve chapters
3, 4, 5

# Pandas

for data analytics

In [ ]:
!pip install pandas

In [28]:
import pandas as pd

In [29]:
df = pd.read_csv('nyc_weather.csv')

df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [30]:
type(df)

pandas.core.frame.DataFrame

In [31]:
df['Temperature']

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [32]:
df[['Temperature']]

Temperature
0            38
1            36
2            40
3            25
4            20
5            33
6            39
7            39
8            44
9            50
10           33
11           35
12           26
13           30
14           43
15           47
16           36
17           25
18           22
19           32
20           31
21           26
22           26
23           28
24           34
25           43
26           41
27           37
28           36
29           34
30           46

In [33]:
type(df['Temperature'])

pandas.core.series.Series

In [34]:
df[['Temperature', 'Humidity']]

Temperature  Humidity
0            38        52
1            36        46
2            40        47
3            25        44
4            20        41
5            33        35
6            39        33
7            39        64
8            44        77
9            50        71
10           33        37
11           35        53
12           26        42
13           30        47
14           43        62
15           47        70
16           36        66
17           25        53
18           22        42
19           32        49
20           31        45
21           26        41
22           26        78
23           28        53
24           34        54
25           43        56
26           41        45
27           37        51
28           36        50
29           34        46
30           46        52

In [35]:
type(df[['Temperature']])

pandas.core.frame.DataFrame

In [36]:
df['Temperature'][0]

38

In [37]:
type(df['Temperature'][0]) # 8 bytes -> 64 bits

numpy.int64

In [38]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [39]:
df['Temperature'].max()

50

In [40]:
df['Temperature'].mean()

34.67741935483871

In [41]:
df.shape

(31, 11)

In [42]:
df.size

341

In [43]:
df.ndim

2

In [44]:
df.head()

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [45]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

### operations

dictionary -> JSON

In [46]:
weather_data = {
    'day': ['1/1/2024', '1/2/2024', '1/3/2024', '1/4/2024', '1/5/2024', '1/6/2024'],
    'temperature': [32,35,28,24,32,38],
    'windspeed': [6,7,8,2,4,3],
    'event': ['Rain', "Sunny", 'Snow','Rain', "Sunny", 'Snow']
}

df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2024           32          6   Rain
1  1/2/2024           35          7  Sunny
2  1/3/2024           28          8   Snow
3  1/4/2024           24          2   Rain
4  1/5/2024           32          4  Sunny
5  1/6/2024           38          3   Snow

In [47]:
df.set_index('day')

temperature  windspeed  event
day                                    
1/1/2024           32          6   Rain
1/2/2024           35          7  Sunny
1/3/2024           28          8   Snow
1/4/2024           24          2   Rain
1/5/2024           32          4  Sunny
1/6/2024           38          3   Snow

In [48]:
df

day  temperature  windspeed  event
0  1/1/2024           32          6   Rain
1  1/2/2024           35          7  Sunny
2  1/3/2024           28          8   Snow
3  1/4/2024           24          2   Rain
4  1/5/2024           32          4  Sunny
5  1/6/2024           38          3   Snow

In [49]:
df.set_index('day', inplace=True)

In [50]:
df

temperature  windspeed  event
day                                    
1/1/2024           32          6   Rain
1/2/2024           35          7  Sunny
1/3/2024           28          8   Snow
1/4/2024           24          2   Rain
1/5/2024           32          4  Sunny
1/6/2024           38          3   Snow

In [51]:
df.columns

Index(['temperature', 'windspeed', 'event'], dtype='object')

In [52]:
df.index

Index(['1/1/2024', '1/2/2024', '1/3/2024', '1/4/2024', '1/5/2024', '1/6/2024'], dtype='object', name='day')

In [53]:
df.loc['1/1/2024']

temperature      32
windspeed         6
event          Rain
Name: 1/1/2024, dtype: object

In [54]:
type(df.loc['1/1/2024'])

pandas.core.series.Series

In [55]:
df.reset_index(inplace=True)

In [56]:
df

day  temperature  windspeed  event
0  1/1/2024           32          6   Rain
1  1/2/2024           35          7  Sunny
2  1/3/2024           28          8   Snow
3  1/4/2024           24          2   Rain
4  1/5/2024           32          4  Sunny
5  1/6/2024           38          3   Snow

In [57]:
df.loc[3]

day            1/4/2024
temperature          24
windspeed             2
event              Rain
Name: 3, dtype: object

### handling missing values

In [58]:
df = pd.read_csv('weather_data2.csv', parse_dates= ['day'])

In [59]:
df

day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [60]:
type(df['day'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [61]:
df.set_index('day', inplace=True)
df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

### fillna

fill not available

In [62]:
new_df = df.fillna(0)

new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [63]:
new_df = df.fillna({
    'temperature': 0,
    'windspeed': 0,
    'event': 'No Event'
})

new_df

temperature  windspeed     event
day                                         
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  No Event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  No Event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

### forward fill

In [64]:
new_df = df.fillna(method='ffill')

new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

### backwardfill

In [65]:
new_df = df.fillna(method='bfill')

new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [66]:
df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

### drop na

In [67]:
new_df = df.dropna()

new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [68]:
new_df = df.dropna(how = 'all')

new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [69]:
new_df = df.dropna(thresh=2)

new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

### replace

In [70]:
df = pd.read_csv('weather_datamissing.csv')
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [71]:
np.nan

nan

In [72]:
new_df = df.replace(-99999, value=np.NaN )

new_df

day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [73]:
new_df = df.replace({
    'temperature': -99999,
    'windspeed': -99999,
    'event': '0'
}, value=np.NaN)

new_df

day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

# Open Source Projects

In [ ]:
Chatbot
- dialogue flow - google
