# Natural Language Processing

https://blog.paperspace.com/pytorch-101-understanding-graphs-and-automatic-differentiation/

In [ ]:
A -> 65 -> binary


In [ ]:
your tshirt is killer

In [ ]:
- intent
- context

Himanshu is here. He is sitting on a chair.

# NLP basics
https://newsletter.himanshuramchandani.co/p/5-alarming-things-you-must-know-about-generativeai-as-a-leader

# Bag of Words

<img src='n1.png' />


In [ ]:
the cat sat on the mat -> [2,1,0,1,1,1]
the dog sat on the cat -> [2,1,1,1,1,0]

# Sequential Representation

<img src='n2.png' />

In [ ]:
[[1,2,3,4],[5,6,7,8]]

while i<5:
    while i<5:
        pass

In [ ]:
O(n2)

# PyTorch 

In [ ]:
- deep learning framework - harware acceleration(GPUs)
- dynamic computational graphs(data structure - Tensors)

In [ ]:
GPT3 - trained 175B parameters

dataset -> 500B tokens

# Tensors

<img src='n3.png' />

<img src='Tensors.png' />

# Word Embeddings

<img src='n2.png' />

# Global Vector for Word Embeddings

https://nlp.stanford.edu/projects/glove/

In [16]:
def loadGlove(path):
    file = open(path, 'r', encoding='utf8')
    model = {}
    
    for l in file:
        line = l.split()
        word = line[0]
        value = np.array([float(val) for val in line[1:]])
        model[word] = value
    
    return model

glove = loadGlove('glove.6B.50d.txt')

In [17]:
glove['python']   # vector embedding for the word Python

array([ 0.5897  , -0.55043 , -1.0106  ,  0.41226 ,  0.57348 ,  0.23464 ,
       -0.35773 , -1.78    ,  0.10745 ,  0.74913 ,  0.45013 ,  1.0351  ,
        0.48348 ,  0.47954 ,  0.51908 , -0.15053 ,  0.32474 ,  1.0789  ,
       -0.90894 ,  0.42943 , -0.56388 ,  0.69961 ,  0.13501 ,  0.16557 ,
       -0.063592,  0.35435 ,  0.42819 ,  0.1536  , -0.47018 , -1.0935  ,
        1.361   , -0.80821 , -0.674   ,  1.2606  ,  0.29554 ,  1.0835  ,
        0.2444  , -1.1877  , -0.60203 , -0.068315,  0.66256 ,  0.45336 ,
       -1.0178  ,  0.68267 , -0.20788 , -0.73393 ,  1.2597  ,  0.15425 ,
       -0.93256 , -0.15025 ])

## How the system know that these words are similar?

Cosine Similarity

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
cosine_similarity(glove['cat'].reshape(1,-1), glove['dog'].reshape(1,-1))

array([[0.92180053]])

In [20]:
cosine_similarity(glove['cat'].reshape(1,-1), glove['piano'].reshape(1,-1))

array([[0.19825255]])

In [23]:
cosine_similarity(glove['king'].reshape(1,-1), glove['queen'].reshape(1,-1))

array([[0.7839043]])

# Tokenization

https://platform.openai.com/tokenizer

# RNN - Recurrent(Feedback) Neural Networks

In [ ]:
Attention Mechanism

Himanshu is here. He is sitting on a chair. 

# Problems with RNNs

In [ ]:
- forward pass - sort-term memory
- backward pass - vanishing gradient problem


# RNN Architectures

In [ ]:
1 - Bidirectional RNN  (BRNN)
2 - Gated Recurrent Unit (GRU)
3 - Long Short Term Memory(LSTM)

# Long Short Term Memory(LSTM)

<img src='l2.png' />

In [ ]:
mechanism -> gates
- it stores relevant information to make predictions

RNN
- words -> vectors -> RNN process it one-by-one -> tanh[-1, 1] -> hidden layer 

[5,0.1,-0.5] -> tanh -> [0.99, 0.009, -0.46]

- small sentences, 
- less computational as compared to LSTM and GRU

# Transformers

<img src='t8.png' />

In [ ]:
transformer use attention to boost the speed, more specifically self-attention

attention -> assign different weights to the input sequence, based on relevant parts

self-attention -> intra-attention/inner attention
                it will assign weigths based on the importance of each element 
                in relation to other within the same sequence.

# Deep Learning Interview Questions

https://github.com/youssefHosni/Data-Science-Interview-Questions-Answers/blob/main/Deep%20Learning%20Questions%20&%20Answers%20for%20Data%20Scientists.md